### ISSUE TITLE
Mixture of matrix fisher distribution

### ISSUE THREAD

**Issue by leilai125** [Davmo049/Public_prob_orientation_estimation_with_matrix_fisher_distributions#4]
Hi, 

Thanks for sharing! 

I have a question. Each matrix fisher distribution is determined by the parameters, i.e. an unconstraint 3*3 matrix F. If I have two matrix fisher distributions with paraemters F1 and F2 respectively, how do I obtain the mixture of these two matix fisher distributions? 

Thank you very much!

**Comment by Davmo049** [comment]
I will close this since this work did not use mixture models.
